#ifndef _INFINITY_CHARGING_CONTROL_H
#define _INFINITY_CHARGING_CONTROL_H

#include <linux/ioctl.h>

#define CHARGING_CTRL_OFF    0
#define CHARGING_CTRL_ON     1
#define CHARGING_CTRL_PAUSE  2
#define CHARGING_CTRL_LIMIT  3
#define CHARGING_CTRL_BYPASS 4

#define INFINITY_CHARGE_IOC_MAGIC 'I'
#define INFINITY_CHARGE_SET_MODE _IOW(INFINITY_CHARGE_IOC_MAGIC, 1, int)
#define INFINITY_CHARGE_GET_MODE _IOR(INFINITY_CHARGE_IOC_MAGIC, 2, int)
#define INFINITY_CHARGE_SET_LIMIT _IOW(INFINITY_CHARGE_IOC_MAGIC, 3, int)

#endif
